/* Generated by tools/gen_msgram.py. Do not edit. */
#ifndef JOINT_MSGRAM_VECTORS_H
#define JOINT_MSGRAM_VECTORS_H

#include <stdint.h>

#define MSGRAM_EXPECT_TOTAL_BYTES 2432u
#define MSGRAM_EXPECT_FREE_BYTES  7808u

typedef struct {
    const char *name;
    uint32_t    elements;
    uint32_t    element_bytes;
    uint32_t    bytes;
    uint32_t    offset;
} msgram_vector_t;

static const msgram_vector_t MSGRAM_VECTORS[] = {
    { "std_filters", 8u, 4u, 32u, 0u },
    { "ext_filters", 4u, 8u, 32u, 32u },
    { "rx_fifo0", 16u, 72u, 1152u, 64u },
    { "rx_fifo1", 8u, 72u, 576u, 1216u },
    { "rx_buffers", 0u, 72u, 0u, 1792u },
    { "tx_event", 8u, 8u, 64u, 1792u },
    { "tx_buffers", 8u, 72u, 576u, 1856u },
};

#define MSGRAM_VECTOR_COUNT ((int) (sizeof MSGRAM_VECTORS / sizeof MSGRAM_VECTORS[0]))

#endif /* JOINT_MSGRAM_VECTORS_H */
