/* Generated by tools/gen_frame_vectors.py. Do not edit. */
#ifndef JOINT_FRAME_VECTORS_H
#define JOINT_FRAME_VECTORS_H

#include <stdbool.h>
#include <stdint.h>

/* Code 0 to 15, as each format reads it. -1 means the format has no
   length for that code, which never happens: both always have one. */
typedef struct {
    uint8_t code;
    int32_t classic_length;
    int32_t fd_length;
} frame_code_vector_t;

static const frame_code_vector_t FRAME_CODE_VECTORS[] = {
    { 0u, 0, 0 },
    { 1u, 1, 1 },
    { 2u, 2, 2 },
    { 3u, 3, 3 },
    { 4u, 4, 4 },
    { 5u, 5, 5 },
    { 6u, 6, 6 },
    { 7u, 7, 7 },
    { 8u, 8, 8 },
    { 9u, 8, 12 },
    { 10u, 8, 16 },
    { 11u, 8, 20 },
    { 12u, 8, 24 },
    { 13u, 8, 32 },
    { 14u, 8, 48 },
    { 15u, 8, 64 },
};

/* Every length from 0 to 64, and the code each format gives it.
   -1 means the format cannot carry that length at all. */
typedef struct {
    uint32_t length;
    int32_t  classic_code;
    int32_t  fd_code;
} frame_length_vector_t;

static const frame_length_vector_t FRAME_LENGTH_VECTORS[] = {
    { 0u, 0, 0 },
    { 1u, 1, 1 },
    { 2u, 2, 2 },
    { 3u, 3, 3 },
    { 4u, 4, 4 },
    { 5u, 5, 5 },
    { 6u, 6, 6 },
    { 7u, 7, 7 },
    { 8u, 8, 8 },
    { 9u, -1, -1 },
    { 10u, -1, -1 },
    { 11u, -1, -1 },
    { 12u, -1, 9 },
    { 13u, -1, -1 },
    { 14u, -1, -1 },
    { 15u, -1, -1 },
    { 16u, -1, 10 },
    { 17u, -1, -1 },
    { 18u, -1, -1 },
    { 19u, -1, -1 },
    { 20u, -1, 11 },
    { 21u, -1, -1 },
    { 22u, -1, -1 },
    { 23u, -1, -1 },
    { 24u, -1, 12 },
    { 25u, -1, -1 },
    { 26u, -1, -1 },
    { 27u, -1, -1 },
    { 28u, -1, -1 },
    { 29u, -1, -1 },
    { 30u, -1, -1 },
    { 31u, -1, -1 },
    { 32u, -1, 13 },
    { 33u, -1, -1 },
    { 34u, -1, -1 },
    { 35u, -1, -1 },
    { 36u, -1, -1 },
    { 37u, -1, -1 },
    { 38u, -1, -1 },
    { 39u, -1, -1 },
    { 40u, -1, -1 },
    { 41u, -1, -1 },
    { 42u, -1, -1 },
    { 43u, -1, -1 },
    { 44u, -1, -1 },
    { 45u, -1, -1 },
    { 46u, -1, -1 },
    { 47u, -1, -1 },
    { 48u, -1, 14 },
    { 49u, -1, -1 },
    { 50u, -1, -1 },
    { 51u, -1, -1 },
    { 52u, -1, -1 },
    { 53u, -1, -1 },
    { 54u, -1, -1 },
    { 55u, -1, -1 },
    { 56u, -1, -1 },
    { 57u, -1, -1 },
    { 58u, -1, -1 },
    { 59u, -1, -1 },
    { 60u, -1, -1 },
    { 61u, -1, -1 },
    { 62u, -1, -1 },
    { 63u, -1, -1 },
    { 64u, -1, 15 },
};

typedef struct {
    const char *label;
    uint32_t    length;
    bool        fd;
    bool        brs;
    bool        ok;
    int32_t     code;
} frame_vector_t;

static const frame_vector_t FRAME_VECTORS[] = {
    { "classic, 8 bytes", 8u, false, false, true, 8 },
    { "flexible-data, 64 bytes, no rate switch", 64u, true, false, true, 15 },
    { "flexible-data, 64 bytes, rate switch", 64u, true, true, true, 15 },
    { "REFUSE, classic cannot carry 12 bytes", 12u, false, false, false, -1 },
    { "REFUSE, 9 bytes has no code in either format", 9u, true, false, false, -1 },
    { "REFUSE, the rate switch without the format", 8u, false, true, false, -1 },
    { "REFUSE, 65 bytes is past the largest code", 65u, true, false, false, -1 },
};

#define FRAME_CODE_VECTOR_COUNT ((int) (sizeof FRAME_CODE_VECTORS / sizeof FRAME_CODE_VECTORS[0]))
#define FRAME_LENGTH_VECTOR_COUNT ((int) (sizeof FRAME_LENGTH_VECTORS / sizeof FRAME_LENGTH_VECTORS[0]))
#define FRAME_VECTOR_COUNT ((int) (sizeof FRAME_VECTORS / sizeof FRAME_VECTORS[0]))

#endif /* JOINT_FRAME_VECTORS_H */
