/* Generated by tools/gen_bt_vectors.py. Do not edit. */
#ifndef JOINT_BT_VECTORS_H
#define JOINT_BT_VECTORS_H

#include <stdbool.h>
#include <stdint.h>

typedef struct {
    const char *label;
    uint32_t    kernel_hz;
    uint32_t    bitrate;
    uint32_t    want_sp_permille;
    bool        data_phase;   /* false: nominal */
    bool        ok;
    uint32_t    prescaler;
    uint32_t    seg1;
    uint32_t    seg2;
    uint32_t    sjw;
    uint32_t    sample_point_permille;
} bt_vector_t;

static const bt_vector_t BT_VECTORS[] = {
    { "design nominal, 80 MHz", 80000000u, 500000u, 800u, false, true, 1u, 127u, 32u, 32u, 800u },
    { "design data, 80 MHz", 80000000u, 2000000u, 750u, true, true, 1u, 29u, 10u, 10u, 750u },
    { "nominal at 100 MHz", 100000000u, 500000u, 800u, false, true, 1u, 159u, 40u, 40u, 800u },
    { "data at 100 MHz", 100000000u, 2000000u, 750u, true, true, 2u, 18u, 6u, 6u, 760u },
    { "nominal at 60 MHz", 60000000u, 500000u, 800u, false, true, 1u, 95u, 24u, 24u, 800u },
    { "data at 60 MHz", 60000000u, 2000000u, 750u, true, true, 1u, 22u, 7u, 7u, 767u },
    { "nominal at 40 MHz", 40000000u, 500000u, 800u, false, true, 1u, 63u, 16u, 16u, 800u },
    { "data at 40 MHz", 40000000u, 2000000u, 750u, true, true, 1u, 14u, 5u, 5u, 750u },
    { "nominal, 1 Mbit/s at 80 MHz", 80000000u, 1000000u, 800u, false, true, 1u, 63u, 16u, 16u, 800u },
    { "data, 5 Mbit/s at 80 MHz", 80000000u, 5000000u, 750u, true, true, 1u, 11u, 4u, 4u, 750u },
    { "data, 8 Mbit/s at 80 MHz", 80000000u, 8000000u, 750u, true, true, 1u, 7u, 2u, 2u, 800u },
    { "REFUSE, the bit rate does not divide the quantum rate", 80000000u, 666667u, 800u, false, false, 0u, 0u, 0u, 0u, 0u },
    { "REFUSE, no prescaler divides this kernel clock into this bit rate", 33000000u, 2000000u, 750u, true, false, 0u, 0u, 0u, 0u, 0u },
    { "REFUSE, 3 quanta a bit is legal but below this volume's floor", 6000000u, 2000000u, 750u, true, false, 0u, 0u, 0u, 0u, 0u },
    { "REFUSE, 2 quanta a bit is below what the registers can hold", 80000000u, 40000000u, 750u, true, false, 0u, 0u, 0u, 0u, 0u },
};

#define BT_VECTOR_COUNT ((int) (sizeof BT_VECTORS / sizeof BT_VECTORS[0]))

#endif /* JOINT_BT_VECTORS_H */
