/* Generated by tools/gen_initplan.py. Do not edit. */
#ifndef JOINT_INITPLAN_VECTORS_H
#define JOINT_INITPLAN_VECTORS_H

#include <stdbool.h>
#include <stdint.h>

typedef struct {
    uint32_t    op;
    uint32_t    reg;
    uint32_t    mask;
    uint32_t    value;
} ip_step_t;

typedef struct {
    const char     *label;
    uint32_t        kernel_hz;
    uint32_t        bitrate;
    uint32_t        want_sp_permille;
    uint32_t        mode;
    bool            one_shot;
    bool            ok;
    uint32_t        step_count;
    const ip_step_t *steps;
} ip_vector_t;

static const ip_step_t IP_STEPS_0[] = {
    { 0u, 0x000u, 0x00000000u, 0x00000000u },   /* core release, and which M_CAN version this part carries */
    { 6u, 0x004u, 0xFFFFFFFFu, 0x87654321u },   /* endianness, the one register with one answer */
    { 2u, 0x018u, 0x00000001u, 0x00000001u },   /* stop the peripheral */
    { 3u, 0x018u, 0x00000001u, 0x00000000u },   /* wait for it to be stopped */
    { 5u, 0x000u, 0x00000980u, 0x00000000u },   /* clear every word of the message RAM in use */
    { 2u, 0x018u, 0x00000002u, 0x00000002u },   /* open configuration */
    { 3u, 0x018u, 0x00000002u, 0x00000000u },   /* wait for configuration to be open */
    { 1u, 0x0BCu, 0x00000000u, 0x00000777u },   /* receive elements are 64 byte */
    { 1u, 0x0C8u, 0x00000000u, 0x00000007u },   /* transmit elements are 64 byte */
    { 1u, 0x080u, 0x00000000u, 0x00000000u },   /* accept every non-matching frame into receive FIFO 0 */
    { 1u, 0x084u, 0x00000000u, 0x00080000u },   /* standard filter list */
    { 1u, 0x088u, 0x00000000u, 0x00040020u },   /* extended filter list */
    { 1u, 0x0A0u, 0x00000000u, 0x00100040u },   /* receive FIFO 0 */
    { 1u, 0x0B0u, 0x00000000u, 0x000804C0u },   /* receive FIFO 1 */
    { 1u, 0x0ACu, 0x00000000u, 0x00000700u },   /* receive buffers, none of them */
    { 1u, 0x0F0u, 0x00000000u, 0x00080700u },   /* transmit event FIFO */
    { 1u, 0x0C0u, 0x00000000u, 0x08000740u },   /* transmit FIFO or queue */
    { 2u, 0x018u, 0x000083E4u, 0x00000000u },   /* the mode bits */
    { 1u, 0x010u, 0x00000000u, 0x00000000u },   /* the test register, writable only now */
    { 1u, 0x01Cu, 0x00000000u, 0x04000B02u },   /* nominal bit timing */
    { 2u, 0x018u, 0x00000002u, 0x00000000u },   /* close configuration */
    { 2u, 0x018u, 0x00000001u, 0x00000000u },   /* start */
    { 4u, 0x018u, 0x00000001u, 0x00000000u },   /* wait until it is running */
};

static const ip_step_t IP_STEPS_1[] = {
    { 0u, 0x000u, 0x00000000u, 0x00000000u },   /* core release, and which M_CAN version this part carries */
    { 6u, 0x004u, 0xFFFFFFFFu, 0x87654321u },   /* endianness, the one register with one answer */
    { 2u, 0x018u, 0x00000001u, 0x00000001u },   /* stop the peripheral */
    { 3u, 0x018u, 0x00000001u, 0x00000000u },   /* wait for it to be stopped */
    { 5u, 0x000u, 0x00000980u, 0x00000000u },   /* clear every word of the message RAM in use */
    { 2u, 0x018u, 0x00000002u, 0x00000002u },   /* open configuration */
    { 3u, 0x018u, 0x00000002u, 0x00000000u },   /* wait for configuration to be open */
    { 1u, 0x0BCu, 0x00000000u, 0x00000777u },   /* receive elements are 64 byte */
    { 1u, 0x0C8u, 0x00000000u, 0x00000007u },   /* transmit elements are 64 byte */
    { 1u, 0x080u, 0x00000000u, 0x00000000u },   /* accept every non-matching frame into receive FIFO 0 */
    { 1u, 0x084u, 0x00000000u, 0x00080000u },   /* standard filter list */
    { 1u, 0x088u, 0x00000000u, 0x00040020u },   /* extended filter list */
    { 1u, 0x0A0u, 0x00000000u, 0x00100040u },   /* receive FIFO 0 */
    { 1u, 0x0B0u, 0x00000000u, 0x000804C0u },   /* receive FIFO 1 */
    { 1u, 0x0ACu, 0x00000000u, 0x00000700u },   /* receive buffers, none of them */
    { 1u, 0x0F0u, 0x00000000u, 0x00080700u },   /* transmit event FIFO */
    { 1u, 0x0C0u, 0x00000000u, 0x08000740u },   /* transmit FIFO or queue */
    { 2u, 0x018u, 0x000083E4u, 0x000000A0u },   /* the mode bits */
    { 1u, 0x010u, 0x00000000u, 0x00000010u },   /* the test register, writable only now */
    { 1u, 0x01Cu, 0x00000000u, 0x04000B02u },   /* nominal bit timing */
    { 2u, 0x018u, 0x00000002u, 0x00000000u },   /* close configuration */
    { 2u, 0x018u, 0x00000001u, 0x00000000u },   /* start */
    { 4u, 0x018u, 0x00000001u, 0x00000000u },   /* wait until it is running */
};

static const ip_step_t IP_STEPS_2[] = {
    { 0u, 0x000u, 0x00000000u, 0x00000000u },   /* core release, and which M_CAN version this part carries */
    { 6u, 0x004u, 0xFFFFFFFFu, 0x87654321u },   /* endianness, the one register with one answer */
    { 2u, 0x018u, 0x00000001u, 0x00000001u },   /* stop the peripheral */
    { 3u, 0x018u, 0x00000001u, 0x00000000u },   /* wait for it to be stopped */
    { 5u, 0x000u, 0x00000980u, 0x00000000u },   /* clear every word of the message RAM in use */
    { 2u, 0x018u, 0x00000002u, 0x00000002u },   /* open configuration */
    { 3u, 0x018u, 0x00000002u, 0x00000000u },   /* wait for configuration to be open */
    { 1u, 0x0BCu, 0x00000000u, 0x00000777u },   /* receive elements are 64 byte */
    { 1u, 0x0C8u, 0x00000000u, 0x00000007u },   /* transmit elements are 64 byte */
    { 1u, 0x080u, 0x00000000u, 0x00000000u },   /* accept every non-matching frame into receive FIFO 0 */
    { 1u, 0x084u, 0x00000000u, 0x00080000u },   /* standard filter list */
    { 1u, 0x088u, 0x00000000u, 0x00040020u },   /* extended filter list */
    { 1u, 0x0A0u, 0x00000000u, 0x00100040u },   /* receive FIFO 0 */
    { 1u, 0x0B0u, 0x00000000u, 0x000804C0u },   /* receive FIFO 1 */
    { 1u, 0x0ACu, 0x00000000u, 0x00000700u },   /* receive buffers, none of them */
    { 1u, 0x0F0u, 0x00000000u, 0x00080700u },   /* transmit event FIFO */
    { 1u, 0x0C0u, 0x00000000u, 0x08000740u },   /* transmit FIFO or queue */
    { 2u, 0x018u, 0x000083E4u, 0x00000080u },   /* the mode bits */
    { 1u, 0x010u, 0x00000000u, 0x00000010u },   /* the test register, writable only now */
    { 1u, 0x01Cu, 0x00000000u, 0x04000B02u },   /* nominal bit timing */
    { 2u, 0x018u, 0x00000002u, 0x00000000u },   /* close configuration */
    { 2u, 0x018u, 0x00000001u, 0x00000000u },   /* start */
    { 4u, 0x018u, 0x00000001u, 0x00000000u },   /* wait until it is running */
};

static const ip_step_t IP_STEPS_3[] = {
    { 0u, 0x000u, 0x00000000u, 0x00000000u },   /* core release, and which M_CAN version this part carries */
    { 6u, 0x004u, 0xFFFFFFFFu, 0x87654321u },   /* endianness, the one register with one answer */
    { 2u, 0x018u, 0x00000001u, 0x00000001u },   /* stop the peripheral */
    { 3u, 0x018u, 0x00000001u, 0x00000000u },   /* wait for it to be stopped */
    { 5u, 0x000u, 0x00000980u, 0x00000000u },   /* clear every word of the message RAM in use */
    { 2u, 0x018u, 0x00000002u, 0x00000002u },   /* open configuration */
    { 3u, 0x018u, 0x00000002u, 0x00000000u },   /* wait for configuration to be open */
    { 1u, 0x0BCu, 0x00000000u, 0x00000777u },   /* receive elements are 64 byte */
    { 1u, 0x0C8u, 0x00000000u, 0x00000007u },   /* transmit elements are 64 byte */
    { 1u, 0x080u, 0x00000000u, 0x00000000u },   /* accept every non-matching frame into receive FIFO 0 */
    { 1u, 0x084u, 0x00000000u, 0x00080000u },   /* standard filter list */
    { 1u, 0x088u, 0x00000000u, 0x00040020u },   /* extended filter list */
    { 1u, 0x0A0u, 0x00000000u, 0x00100040u },   /* receive FIFO 0 */
    { 1u, 0x0B0u, 0x00000000u, 0x000804C0u },   /* receive FIFO 1 */
    { 1u, 0x0ACu, 0x00000000u, 0x00000700u },   /* receive buffers, none of them */
    { 1u, 0x0F0u, 0x00000000u, 0x00080700u },   /* transmit event FIFO */
    { 1u, 0x0C0u, 0x00000000u, 0x08000740u },   /* transmit FIFO or queue */
    { 2u, 0x018u, 0x000083E4u, 0x00000020u },   /* the mode bits */
    { 1u, 0x010u, 0x00000000u, 0x00000000u },   /* the test register, writable only now */
    { 1u, 0x01Cu, 0x00000000u, 0x04000B02u },   /* nominal bit timing */
    { 2u, 0x018u, 0x00000002u, 0x00000000u },   /* close configuration */
    { 2u, 0x018u, 0x00000001u, 0x00000000u },   /* start */
    { 4u, 0x018u, 0x00000001u, 0x00000000u },   /* wait until it is running */
};

static const ip_step_t IP_STEPS_4[] = {
    { 0u, 0x000u, 0x00000000u, 0x00000000u },   /* core release, and which M_CAN version this part carries */
    { 6u, 0x004u, 0xFFFFFFFFu, 0x87654321u },   /* endianness, the one register with one answer */
    { 2u, 0x018u, 0x00000001u, 0x00000001u },   /* stop the peripheral */
    { 3u, 0x018u, 0x00000001u, 0x00000000u },   /* wait for it to be stopped */
    { 5u, 0x000u, 0x00000980u, 0x00000000u },   /* clear every word of the message RAM in use */
    { 2u, 0x018u, 0x00000002u, 0x00000002u },   /* open configuration */
    { 3u, 0x018u, 0x00000002u, 0x00000000u },   /* wait for configuration to be open */
    { 1u, 0x0BCu, 0x00000000u, 0x00000777u },   /* receive elements are 64 byte */
    { 1u, 0x0C8u, 0x00000000u, 0x00000007u },   /* transmit elements are 64 byte */
    { 1u, 0x080u, 0x00000000u, 0x00000000u },   /* accept every non-matching frame into receive FIFO 0 */
    { 1u, 0x084u, 0x00000000u, 0x00080000u },   /* standard filter list */
    { 1u, 0x088u, 0x00000000u, 0x00040020u },   /* extended filter list */
    { 1u, 0x0A0u, 0x00000000u, 0x00100040u },   /* receive FIFO 0 */
    { 1u, 0x0B0u, 0x00000000u, 0x000804C0u },   /* receive FIFO 1 */
    { 1u, 0x0ACu, 0x00000000u, 0x00000700u },   /* receive buffers, none of them */
    { 1u, 0x0F0u, 0x00000000u, 0x00080700u },   /* transmit event FIFO */
    { 1u, 0x0C0u, 0x00000000u, 0x08000740u },   /* transmit FIFO or queue */
    { 2u, 0x018u, 0x000083E4u, 0x00000040u },   /* the mode bits */
    { 1u, 0x010u, 0x00000000u, 0x00000000u },   /* the test register, writable only now */
    { 1u, 0x01Cu, 0x00000000u, 0x04000B02u },   /* nominal bit timing */
    { 2u, 0x018u, 0x00000002u, 0x00000000u },   /* close configuration */
    { 2u, 0x018u, 0x00000001u, 0x00000000u },   /* start */
    { 4u, 0x018u, 0x00000001u, 0x00000000u },   /* wait until it is running */
};

static const ip_step_t IP_STEPS_5[] = {
    { 0u, 0x000u, 0x00000000u, 0x00000000u },   /* core release, and which M_CAN version this part carries */
    { 6u, 0x004u, 0xFFFFFFFFu, 0x87654321u },   /* endianness, the one register with one answer */
    { 2u, 0x018u, 0x00000001u, 0x00000001u },   /* stop the peripheral */
    { 3u, 0x018u, 0x00000001u, 0x00000000u },   /* wait for it to be stopped */
    { 5u, 0x000u, 0x00000980u, 0x00000000u },   /* clear every word of the message RAM in use */
    { 2u, 0x018u, 0x00000002u, 0x00000002u },   /* open configuration */
    { 3u, 0x018u, 0x00000002u, 0x00000000u },   /* wait for configuration to be open */
    { 1u, 0x0BCu, 0x00000000u, 0x00000777u },   /* receive elements are 64 byte */
    { 1u, 0x0C8u, 0x00000000u, 0x00000007u },   /* transmit elements are 64 byte */
    { 1u, 0x080u, 0x00000000u, 0x00000000u },   /* accept every non-matching frame into receive FIFO 0 */
    { 1u, 0x084u, 0x00000000u, 0x00080000u },   /* standard filter list */
    { 1u, 0x088u, 0x00000000u, 0x00040020u },   /* extended filter list */
    { 1u, 0x0A0u, 0x00000000u, 0x00100040u },   /* receive FIFO 0 */
    { 1u, 0x0B0u, 0x00000000u, 0x000804C0u },   /* receive FIFO 1 */
    { 1u, 0x0ACu, 0x00000000u, 0x00000700u },   /* receive buffers, none of them */
    { 1u, 0x0F0u, 0x00000000u, 0x00080700u },   /* transmit event FIFO */
    { 1u, 0x0C0u, 0x00000000u, 0x08000740u },   /* transmit FIFO or queue */
    { 2u, 0x018u, 0x000083E4u, 0x00000000u },   /* the mode bits */
    { 1u, 0x010u, 0x00000000u, 0x00000000u },   /* the test register, writable only now */
    { 1u, 0x01Cu, 0x00000000u, 0x0A001805u },   /* nominal bit timing */
    { 2u, 0x018u, 0x00000002u, 0x00000000u },   /* close configuration */
    { 2u, 0x018u, 0x00000001u, 0x00000000u },   /* start */
    { 4u, 0x018u, 0x00000001u, 0x00000000u },   /* wait until it is running */
};

static const ip_vector_t IP_VECTORS[] = {
    { "the first image: classic, 500 kbit/s from the 8 MHz HSE, on the bus", 8000000u, 500000u, 800u, 0u, false, true, 23u, IP_STEPS_0 },
    { "the same, in internal loopback, which needs no bus at all", 8000000u, 500000u, 800u, 1u, false, true, 23u, IP_STEPS_1 },
    { "the same, in external loopback, which puts it on the wire", 8000000u, 500000u, 800u, 2u, false, true, 23u, IP_STEPS_2 },
    { "listening only, which receives and never acknowledges", 8000000u, 500000u, 800u, 3u, false, true, 23u, IP_STEPS_3 },
    { "one shot, no automatic retransmission", 8000000u, 500000u, 800u, 0u, true, true, 23u, IP_STEPS_4 },
    { "the fallback rate, 250 kbit/s", 8000000u, 250000u, 800u, 0u, false, true, 23u, IP_STEPS_5 },
    { "REFUSE, a bit rate the 8 MHz HSE cannot divide into exactly", 8000000u, 666667u, 800u, 0u, false, false, 0u, 0 },
    { "REFUSE, 2 Mbit/s nominal from 8 MHz is 4 quanta, below the floor", 8000000u, 2000000u, 800u, 0u, false, false, 0u, 0 },
};

#define IP_VECTOR_COUNT ((int) (sizeof IP_VECTORS / sizeof IP_VECTORS[0]))

#endif /* JOINT_INITPLAN_VECTORS_H */
