#!/usr/bin/env python3
"""The length code, the frame rules, and the vectors the C must reproduce.

    python tools/gen_frame_vectors.py           regenerate the vectors
    python tools/gen_frame_vectors.py --check   fail if the committed ones differ
    python tools/gen_frame_vectors.py --table   the table for doc/frame-rules.md

Chapter 9 step 4 sends a frame to itself three times: a classic frame, a
flexible-data frame without the rate switch, and one with it. All three have to
build a frame before any of them can send one, and the part of that which can be
proven on a host is the length code and the rules about which combinations are
legal at all.

The controller does not carry a length. It carries a four bit code, and the code
is not the length: code 9 means twelve bytes, and the step from code 12 to code
15 is 24, 32, 48, 64. Worse, the same code means different things in the two
frame formats, because a classic frame has no lengths above eight and clamps
every code above 8 to 8. A codec that gets this wrong does not fail: it moves
the right bytes with the wrong count, or the wrong bytes with the right one.

Python, the exception the house rule allows for orchestration. The node's own
copy is C in src/bus/frame.c and both are checked against the vector file rather
than against each other.
"""
import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
VECTORS_JSON = HERE / "test" / "vectors_frame.json"
VECTORS_H = HERE / "test" / "vectors_frame.h"

# Code 0 to 15, as the flexible-data format reads them.
FD_LENGTH_FOR_CODE = (0, 1, 2, 3, 4, 5, 6, 7, 8, 12, 16, 20, 24, 32, 48, 64)

# The lengths a flexible-data frame can carry. Every other length has no code.
ALLOWED_FD_LENGTHS = FD_LENGTH_FOR_CODE
CLASSIC_MAX = 8


def length_for_code(code, fd):
    """Bytes a code stands for. A classic frame clamps every code above 8."""
    if not 0 <= code <= 15:
        return None
    if fd:
        return FD_LENGTH_FOR_CODE[code]
    return code if code <= CLASSIC_MAX else CLASSIC_MAX


def code_for_length(length, fd):
    """The code for a length, or None when the format cannot carry it.

    Returning None rather than the next code up is the whole point. Rounding a
    length up to the next code silently sends bytes the caller never wrote, and
    rounding down silently drops the tail.
    """
    if length < 0:
        return None
    if not fd:
        return length if length <= CLASSIC_MAX else None
    if length not in ALLOWED_FD_LENGTHS:
        return None
    return FD_LENGTH_FOR_CODE.index(length)


def frame_ok(length, fd, brs):
    """Whether this combination is a frame the controller can be asked to send."""
    if brs and not fd:
        # The rate switch is a flexible-data feature. A classic frame has one
        # rate for the whole frame and nowhere to record a second.
        return False
    return code_for_length(length, fd) is not None


def build():
    codes = []
    for code in range(16):
        codes.append({
            "code": code,
            "classic_length": length_for_code(code, False),
            "fd_length": length_for_code(code, True),
        })

    lengths = []
    for length in range(0, 65):
        lengths.append({
            "length": length,
            "classic_code": code_for_length(length, False),
            "fd_code": code_for_length(length, True),
        })

    # Chapter 9 step 4 sends these three, in this order.
    frames = [
        {"label": "classic, 8 bytes", "length": 8, "fd": False, "brs": False},
        {"label": "flexible-data, 64 bytes, no rate switch",
         "length": 64, "fd": True, "brs": False},
        {"label": "flexible-data, 64 bytes, rate switch",
         "length": 64, "fd": True, "brs": True},
        # Combinations that have to be refused.
        {"label": "REFUSE, classic cannot carry 12 bytes",
         "length": 12, "fd": False, "brs": False},
        {"label": "REFUSE, 9 bytes has no code in either format",
         "length": 9, "fd": True, "brs": False},
        {"label": "REFUSE, the rate switch without the format",
         "length": 8, "fd": False, "brs": True},
        {"label": "REFUSE, 65 bytes is past the largest code",
         "length": 65, "fd": True, "brs": False},
    ]
    for f in frames:
        f["ok"] = frame_ok(f["length"], f["fd"], f["brs"])
        f["code"] = code_for_length(f["length"], f["fd"]) if f["ok"] else None

    return {
        "note": "Generated by tools/gen_frame_vectors.py. Do not edit.",
        "fd_length_for_code": list(FD_LENGTH_FOR_CODE),
        "classic_max": CLASSIC_MAX,
        "codes": codes,
        "lengths": lengths,
        "frames": frames,
    }


def as_header(doc):
    lines = [
        "/* Generated by tools/gen_frame_vectors.py. Do not edit. */",
        "#ifndef JOINT_FRAME_VECTORS_H",
        "#define JOINT_FRAME_VECTORS_H",
        "",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "",
        "/* Code 0 to 15, as each format reads it. -1 means the format has no",
        "   length for that code, which never happens: both always have one. */",
        "typedef struct {",
        "    uint8_t code;",
        "    int32_t classic_length;",
        "    int32_t fd_length;",
        "} frame_code_vector_t;",
        "",
        "static const frame_code_vector_t FRAME_CODE_VECTORS[] = {",
    ]
    for c in doc["codes"]:
        lines.append("    {{ {c}u, {cl}, {fl} }},".format(
            c=c["code"], cl=c["classic_length"], fl=c["fd_length"]))
    lines += [
        "};",
        "",
        "/* Every length from 0 to 64, and the code each format gives it.",
        "   -1 means the format cannot carry that length at all. */",
        "typedef struct {",
        "    uint32_t length;",
        "    int32_t  classic_code;",
        "    int32_t  fd_code;",
        "} frame_length_vector_t;",
        "",
        "static const frame_length_vector_t FRAME_LENGTH_VECTORS[] = {",
    ]
    for l in doc["lengths"]:
        cc = -1 if l["classic_code"] is None else l["classic_code"]
        fc = -1 if l["fd_code"] is None else l["fd_code"]
        lines.append("    {{ {n}u, {cc}, {fc} }},".format(
            n=l["length"], cc=cc, fc=fc))
    lines += [
        "};",
        "",
        "typedef struct {",
        "    const char *label;",
        "    uint32_t    length;",
        "    bool        fd;",
        "    bool        brs;",
        "    bool        ok;",
        "    int32_t     code;",
        "} frame_vector_t;",
        "",
        "static const frame_vector_t FRAME_VECTORS[] = {",
    ]
    for f in doc["frames"]:
        code = -1 if f["code"] is None else f["code"]
        lines.append(
            '    {{ "{lab}", {n}u, {fd}, {brs}, {ok}, {code} }},'.format(
                lab=f["label"], n=f["length"],
                fd="true" if f["fd"] else "false",
                brs="true" if f["brs"] else "false",
                ok="true" if f["ok"] else "false", code=code))
    lines += [
        "};",
        "",
        "#define FRAME_CODE_VECTOR_COUNT "
        "((int) (sizeof FRAME_CODE_VECTORS / sizeof FRAME_CODE_VECTORS[0]))",
        "#define FRAME_LENGTH_VECTOR_COUNT "
        "((int) (sizeof FRAME_LENGTH_VECTORS / sizeof FRAME_LENGTH_VECTORS[0]))",
        "#define FRAME_VECTOR_COUNT "
        "((int) (sizeof FRAME_VECTORS / sizeof FRAME_VECTORS[0]))",
        "",
        "#endif /* JOINT_FRAME_VECTORS_H */",
        "",
    ]
    return "\n".join(lines)


def table(doc):
    rows = ["| Code | Classic reads | Flexible-data reads |", "|---|---|---|"]
    for c in doc["codes"]:
        note = ""
        if c["code"] > CLASSIC_MAX:
            note = " (clamped)"
        rows.append(f"| {c['code']} | {c['classic_length']}{note} | "
                    f"{c['fd_length']} |")
    rows.append("")
    rows.append("| Frame | Legal | Code |")
    rows.append("|---|---|---|")
    for f in doc["frames"]:
        rows.append(f"| {f['label']} | {'yes' if f['ok'] else 'no'} | "
                    f"{'n/a' if f['code'] is None else f['code']} |")
    return "\n".join(rows)


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--table", action="store_true")
    a = ap.parse_args(argv)

    doc = build()
    js = json.dumps(doc, indent=2) + "\n"
    hd = as_header(doc)

    if a.table:
        print(table(doc))
        return 0

    if a.check:
        bad = 0
        for path, want in ((VECTORS_JSON, js), (VECTORS_H, hd)):
            have = path.read_text(encoding="utf-8") if path.exists() else ""
            if have.replace("\r\n", "\n") != want:
                print(f"{path.name} differs from the generator")
                bad += 1
        if bad:
            print("a hand edit does not survive here; regenerate instead")
            return 1
        refused = sum(1 for f in doc["frames"] if not f["ok"])
        print(f"frame vectors match the generator (16 codes, 65 lengths, "
              f"{len(doc['frames'])} frames, {refused} of them refused)")
        return 0

    VECTORS_JSON.parent.mkdir(parents=True, exist_ok=True)
    VECTORS_JSON.write_text(js, encoding="utf-8")
    VECTORS_H.write_text(hd, encoding="utf-8")
    refused = sum(1 for f in doc["frames"] if not f["ok"])
    print(f"wrote {VECTORS_JSON.name} and {VECTORS_H.name}: 16 codes, "
          f"65 lengths, {len(doc['frames'])} frames, {refused} refused")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
